install: sys-suspend sys-hibernate
	install -m 755 sys-suspend /usr/local/bin/sys-suspend
	install -m 755 sys-hibernate /usr/local/bin/sys-hibernate
	@echo "don't forget to visudo and update your permissions!"
